apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJZbkoxYkdrNloyaHdYMWhDUkdWNlMyVllOV1p2WTBsUllrZ3lOVEJNVlZkbk9VNXdaekJxTlRGUVVIWndiQT09IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: ghcr-login
  namespace: pinger-exporter
type: kubernetes.io/dockerconfigjson
