apiVersion: v1
kind: Service
metadata:
    namespace: pinger-exporter
    labels:
        app: pinger-exporter
    name: pinger-exporter
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pinger-exporter
  type: ClusterIP

